### ISSUE TITLE
Integrating testrail with azure hosted mysql database?

### ISSUE THREAD

**Issue by Babu5394** [cnolick/testrail-kubernetes#1]
Hi

I'm planning to setup testrail with Azure Database for MySQL server. Is this possible with this code?

Is yes, could you please explain me how to pass database related details in testrail application?

thanks

**Comment by cnolick** [comment]
hi! 
If u wanna use external db just use Sts testrail and when you first time execute Sts they ask u about your db. next u insert your credentials and profit. in root file kustomize remove mysql resource

**Comment by Babu5394** [comment]
> hi! If u wanna use external db just use Sts testrail and when you first time execute Sts they ask u about your db. next u insert your credentials and profit. in root file kustomize remove mysql resource

I tried with only testrail application using your files and I could see this one
1) ![image](https://user-images.githubusercontent.com/93255287/146412694-f9ce4f43-474b-4993-b8da-cfbc27374fc5.png)
2) 
![image](https://user-images.githubusercontent.com/93255287/146413212-1cef5499-2098-49fb-87cb-52b7d2affe38.png)

I'm getting ssl error. Is there anyway I can pass variable to make SSL DB connection?

**Comment by cnolick** [comment]
I don't know not use azure maybe on this cloud specific setup mysql

**Comment by Babu5394** [comment]
okay thanks for your update.
Did you tried with SSL DB connection?

**Comment by cnolick** [comment]
I use just standard connect.

**Comment by Babu5394** [comment]
One more issue i'm facing with your code,
Could not compute checksum for file "custom/auth/readme.txt": md5_file(/var/www/testrail/custom/auth/readme.txt): failed to open stream: No such file or directory. Please make sure that the file can be read by the web server (permissions). You can also try to copy the TestRail files again (please make sure to stop your web server before).

**Comment by Babu5394** [comment]
I used database which is hosted on kubernetes by your configuration files.
In the installation wizard, what value you gave for Server* (The host name of the database server.)
![image](https://user-images.githubusercontent.com/93255287/146542290-ecd4cf7c-b0bc-4394-b9da-a60dfec18a2e.png)

I tried with serviceip:3306 and servicename.namespace.cluster.local:3306. Is this correct?

![image](https://user-images.githubusercontent.com/93255287/146545062-eaa4701b-e389-47fa-bf2c-915b5a582a6d.png)

**Comment by cnolick** [comment]
I use kubedns

define('DB_DRIVER', 'mysql'); // sqlsrv or mysql
define('DB_HOSTNAME', 'mysql');
define('DB_DATABASE', 'testrail');
define('DB_USERNAME', 'testrail');
define('DB_PASSWORD', 'heresecret');

**Comment by Babu5394** [comment]
One more doubt from side,
I could see the below message in pods,
logs:
No application configuration file found (config.php)

Do I need to create config.php file manually or It will be created automatically based on the values provided during installation wizard setup?
